(function() {var implementors = {};
implementors["dynasm"] = ["impl&lt;T&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='trait core::convert::Into'>Into</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/collections/vec/struct.Vec.html' title='struct collections::vec::Vec'>Vec</a>&lt;T&gt;&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/syntax/util/thin_vec/struct.ThinVec.html' title='struct syntax::util::thin_vec::ThinVec'>ThinVec</a>&lt;T&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='trait core::convert::Into'>Into</a>&lt;<a class='enum' href='https://doc.rust-lang.org/nightly/core/option/enum.Option.html' title='enum core::option::Option'>Option</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/syntax/ptr/struct.P.html' title='struct syntax::ptr::P'>P</a>&lt;<a class='enum' href='https://doc.rust-lang.org/nightly/syntax/ast/enum.PathParameters.html' title='enum syntax::ast::PathParameters'>PathParameters</a>&gt;&gt;&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/syntax/ast/struct.AngleBracketedParameterData.html' title='struct syntax::ast::AngleBracketedParameterData'>AngleBracketedParameterData</a>","impl&lt;T&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='trait core::convert::Into'>Into</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/collections/vec/struct.Vec.html' title='struct collections::vec::Vec'>Vec</a>&lt;T&gt;&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/syntax/ptr/struct.P.html' title='struct syntax::ptr::P'>P</a>&lt;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.slice.html'>[</a>T<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.slice.html'>]</a>&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='trait core::convert::Into'>Into</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/collections/vec/struct.Vec.html' title='struct collections::vec::Vec'>Vec</a>&lt;<a class='enum' href='https://doc.rust-lang.org/nightly/syntax/ext/base/enum.Annotatable.html' title='enum syntax::ext::base::Annotatable'>Annotatable</a>&gt;&gt; for <a class='enum' href='https://doc.rust-lang.org/nightly/syntax/ext/base/enum.Annotatable.html' title='enum syntax::ext::base::Annotatable'>Annotatable</a>",];
implementors["lazy_static"] = [];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
