(function() {var implementors = {};
implementors["dynasm"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html' title='rustc_data_structures::indexed_vec::Idx'>Idx</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/rustc/hir/def_id/struct.CrateNum.html' title='rustc::hir::def_id::CrateNum'>CrateNum</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html' title='rustc_data_structures::indexed_vec::Idx'>Idx</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/rustc/mir/repr/struct.Local.html' title='rustc::mir::repr::Local'>Local</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html' title='rustc_data_structures::indexed_vec::Idx'>Idx</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/rustc/mir/repr/struct.BasicBlock.html' title='rustc::mir::repr::BasicBlock'>BasicBlock</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html' title='rustc_data_structures::indexed_vec::Idx'>Idx</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/rustc/mir/repr/struct.Field.html' title='rustc::mir::repr::Field'>Field</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html' title='rustc_data_structures::indexed_vec::Idx'>Idx</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/rustc/mir/repr/struct.VisibilityScope.html' title='rustc::mir::repr::VisibilityScope'>VisibilityScope</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/rustc_data_structures/indexed_vec/trait.Idx.html' title='rustc_data_structures::indexed_vec::Idx'>Idx</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/rustc/mir/repr/struct.Promoted.html' title='rustc::mir::repr::Promoted'>Promoted</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
